apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "oci://ghcr.io/prometheus-community/charts"
    chart: kube-prometheus-stack
    targetRevision: 77.5.0
    helm:
      valueFiles:
        - values.yaml
      skipTests: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

