apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/salatine/aquarela-devops.git"
    targetRevision: main
    path: k8s/monitoring
    helm:
      valueFiles:
        - values.yaml
      skipTests: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

