kube-prometheus-stack:
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin123
    service:
      type: LoadBalancer
      port: 80

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    alertmanagerSpec:
      replicas: 1
      useExistingSecret: true
      secrets:
        - alertmanager-prometheus-kube-prometheus-alertmanager
