kube-prometheus-stack:
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin123
  alertmanager:
    alertmanagerSpec:
      secrets:
        - 'alertmanager-smtp'
    config:
      global:
        resolve_timeout: 1m
        smtp_smarthost: 'smtp.gmail.com:587'
        smtp_from: 'salatinea@gmail.com'
        smtp_auth_username: 'salatinea@gmail.com'
        smtp_auth_password_file: /etc/alertmanager/secrets/smtp_password
      route:
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 1m
        receiver: 'email-notifications'
        routes: 
        - receiver: 'email-notifications'
          matchers:
            - alertname =~ "TargetDown|KubeSchedulerDown|Watchdog"
      receivers:
        - name: 'email-notifications'
          email_configs:
            - to: 'salatinea@gmail.com'
