kube-prometheus-stack:
  grafana:
    enabled: true
    service:
      type: LoadBalancer
      port: 80

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    alertmanagerSpec:
      replicas: 1
      useExistingSecret: true
      secrets:
        - alertmanager-smtp
    config:
      global:
        resolve_timeout: 1m
        smtp_smarthost: 'smtp.gmail.com:587'
        smtp_from: 'salatinea@gmail.com'
        smtp_auth_username: 'salatinea@gmail.com'
        smtp_auth_password_file: /etc/alertmanager/secrets/smtp_password
      route:
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 1m
        receiver: 'email-notifications'
        routes: []
      receivers:
        - name: 'email-notifications'
          email_configs:
            - to: 'salatinea@gmail.com'
              from: 'salatinea@gmail.com'
              smarthost: 'smtp.gmail.com:587'
              send_resolved: true
              auth_username: 'salatinea@gmail.com'
              auth_password_file: /etc/alertmanager/secrets/smtp_password

