apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-custom-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:465'
      smtp_from: 'seu-email@gmail.com'
      smtp_require_tls: true

    route:
      receiver: 'email-notifications'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'destinatario@gmail.com'
            send_resolved: true
            auth_username:
              name: alertmanager-smtp
              key: smtp_user
            auth_password:
              name: alertmanager-smtp
              key: smtp_password
