apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
spec:
  groups:
  - name: test
    rules:
    - alert: TestEmail
      expr: vector(1)   # sempre verdadeiro
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Teste de envio de email"
        description: ""
