apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-5
  namespace: monitoring
  labels:
    release: "monitoring"
spec:
  groups:
    - name: test5.rules
      rules:
        - alert: TestAlert-5
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "teste alerta"
            description: ""
