fluent-bit:
  serviceAccount:
    create: true

  config:
    service: |
      [SERVICE]
          Flush        1
          Daemon       Off
          Log_Level    info
          Parsers_File parsers.conf

    inputs: |
      [INPUT]
          Name              tail
          Path              /var/log/containers/*.log
          Parser            docker
          Tag               kube.*
          Refresh_Interval  5
          Mem_Buf_Limit     50MB
          Skip_Long_Lines   On
          DB                /var/log/flb_kube.db

    filters: |
      [FILTER]
          Name                kubernetes
          Match               kube.*
          Merge_Log           On
          K8S-Logging.Parser  On
          K8S-Logging.Exclude On

    outputs: |
      [OUTPUT]
          Name  es
          Match kube.*
          Host  elasticsearch-master.logging.svc.cluster.local
          Port  9200
          Index fluentbit
          Type  _doc
          Logstash_Format On
          Replace_Dots    On
          Retry_Limit     False

