on:
  push:
    branches:
      - main

jobs:
  terraform:
    env:
      AWS_REGION: us-east-1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::833565098889:role/desafio_aquarela-eks-role

      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform init
      - run: terraform -chdir=terraform fmt -check -recursive
      - run: terraform -chdir=terraform validate
      - run: terraform -chdir=terraform plan -out=plan.out

      - if: github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform apply -auto-approve plan.out
